<?php
/**
 * Archive: Student Stories — generated by figma-to-wp-4.0 setup/cpt_scaffold.py.
 * Bordered card grid (stjo-story-card styling from the registry).
 *
 * @package stjo
 */

get_header();
?>
<main id="primary" class="site-main">
	<div class="wp-block-group alignfull stjo-page-hero">
		<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
		<h1 class="wp-block-heading has-text-align-center"><?php post_type_archive_title(); ?></h1>
		<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
	</div>
	<hr class="wp-block-separator has-alpha-channel-opacity stjo-zigzag alignfull"/>

	<div class="entry-content">
		<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
		<?php if ( have_posts() ) : ?>
			<div class="wp-block-columns stjo-story-grid">
				<?php
				while ( have_posts() ) :
					the_post();
					?>
					<div class="wp-block-column">
						<article <?php post_class( 'stjo-story-card' ); ?>>
							<?php if ( has_post_thumbnail() ) : ?>
								<figure class="wp-block-image"><?php the_post_thumbnail( 'medium_large' ); ?></figure>
							<?php endif; ?>
							<div class="stjo-story-card__body">
								<h3><?php the_title(); ?></h3>
								<p><?php echo esc_html( get_the_excerpt() ); ?></p>
								<a class="stjo-story-card__more" href="<?php the_permalink(); ?>"><?php esc_html_e( 'Read More', 'stjo' ); ?></a>
							</div>
						</article>
					</div>
				<?php endwhile; ?>
			</div>
			<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
			<?php the_posts_pagination(); ?>
		<?php else : ?>
			<p><?php esc_html_e( 'No stories yet — check back soon.', 'stjo' ); ?></p>
		<?php endif; ?>
		<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
	</div>
</main>
<?php
get_footer();
