<?php
/**
 * Single: Student Story — generated by figma-to-wp-4.0 setup/cpt_scaffold.py.
 *
 * @package stjo
 */

get_header();
?>
<main id="primary" class="site-main">
	<?php
	while ( have_posts() ) :
		the_post();
		?>
		<div class="wp-block-group alignfull stjo-page-hero">
			<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
			<p class="has-text-align-center is-style-eyebrow"><?php echo esc_html( get_post_type_object( get_post_type() )->labels->singular_name ); ?></p>
			<h1 class="wp-block-heading has-text-align-center"><?php the_title(); ?></h1>
			<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
		</div>
		<hr class="wp-block-separator has-alpha-channel-opacity stjo-zigzag alignfull"/>

		<div class="entry-content">
			<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
			<?php if ( has_post_thumbnail() ) : ?>
				<figure class="wp-block-image is-style-rounded"><?php the_post_thumbnail( 'large' ); ?></figure>
			<?php endif; ?>
			<?php the_content(); ?>
			<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
		</div>
	<?php endwhile; ?>
</main>
<?php
get_footer();
