<?php

/**
 * Template part: pre-footer — generated by figma-to-wp-4.0 setup/part_render.py
 * from the 'generosity' registry component. Site-wide band; page patterns
 * skip this component (render_patterns --sitewide).
 *
 * @package stjo
 */
?>
<!-- wp:group {"align":"full","className":"stjo-generosity","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull stjo-generosity"><!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
    <div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->

    <!-- wp:heading {"textAlign":"center","level":2,"textColor":"white"} -->
    <h2 class="wp-block-heading has-text-align-center has-white-color has-text-color">Your Generosity  <strong>Changes Everything</strong></h2>
    <!-- /wp:heading -->

    <!-- wp:paragraph {"align":"center","textColor":"light"} -->
    <p class="has-text-align-center has-light-color has-text-color">Every gift, no matter the size or how you give, brings hope, culture, and opportunity to a Lakota child at St. Joseph's.</p>
    <!-- /wp:paragraph -->

    <!-- wp:spacer {"height":"var:preset|spacing|small"} -->
    <div style="height:var(--wp--preset--spacing--small)" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->

    <!-- wp:columns -->
    <div class="wp-block-columns"><!-- wp:column -->
        <div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url(stjo_asset('card-4.png')); ?>","dimRatio":50,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
            <div class="wp-block-cover stjo-card" style="min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url(stjo_asset('card-4.png')); ?>" data-object-fit="cover" />
                <div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
                    <h3 class="wp-block-heading has-light-color has-text-color">Monthly giving</h3>
                    <!-- /wp:heading -->

                    <!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
                    <p class="has-light-color has-text-color stjo-card__reveal">Be a DreamMaker with a recurring gift</p>
                    <!-- /wp:paragraph -->

                    <!-- wp:buttons -->
                    <div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
                        <div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">Give Monthly Now</a></div>
                        <!-- /wp:button -->
                    </div>
                    <!-- /wp:buttons -->
                </div>
            </div>
            <!-- /wp:cover -->
        </div>
        <!-- /wp:column -->
        <!-- wp:column -->
        <div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url(stjo_asset('card-5.png')); ?>","dimRatio":50,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
            <div class="wp-block-cover stjo-card" style="min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url(stjo_asset('card-5.png')); ?>" data-object-fit="cover" />
                <div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
                    <h3 class="wp-block-heading has-light-color has-text-color">One-Time Gift</h3>
                    <!-- /wp:heading -->

                    <!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
                    <p class="has-light-color has-text-color stjo-card__reveal">Make an immediate impact today</p>
                    <!-- /wp:paragraph -->

                    <!-- wp:buttons -->
                    <div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
                        <div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">Give Now</a></div>
                        <!-- /wp:button -->
                    </div>
                    <!-- /wp:buttons -->
                </div>
            </div>
            <!-- /wp:cover -->
        </div>
        <!-- /wp:column -->
        <!-- wp:column -->
        <div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url(stjo_asset('card-6.png')); ?>","dimRatio":50,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
            <div class="wp-block-cover stjo-card" style="min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url(stjo_asset('card-6.png')); ?>" data-object-fit="cover" />
                <div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
                    <h3 class="wp-block-heading has-light-color has-text-color">Donor  Advised Fund</h3>
                    <!-- /wp:heading -->

                    <!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
                    <p class="has-light-color has-text-color stjo-card__reveal">Give through your DAF account</p>
                    <!-- /wp:paragraph -->

                    <!-- wp:buttons -->
                    <div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
                        <div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">Give Now</a></div>
                        <!-- /wp:button -->
                    </div>
                    <!-- /wp:buttons -->
                </div>
            </div>
            <!-- /wp:cover -->
        </div>
        <!-- /wp:column -->
        <!-- wp:column -->
        <div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url(stjo_asset('card-7.png')); ?>","dimRatio":50,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
            <div class="wp-block-cover stjo-card" style="min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url(stjo_asset('card-7.png')); ?>" data-object-fit="cover" />
                <div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
                    <h3 class="wp-block-heading has-light-color has-text-color">Memorial Gift</h3>
                    <!-- /wp:heading -->

                    <!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
                    <p class="has-light-color has-text-color stjo-card__reveal">Honor a loved one's memory</p>
                    <!-- /wp:paragraph -->

                    <!-- wp:buttons -->
                    <div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
                        <div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">Give Now</a></div>
                        <!-- /wp:button -->
                    </div>
                    <!-- /wp:buttons -->
                </div>
            </div>
            <!-- /wp:cover -->
        </div>
        <!-- /wp:column -->
    </div>
    <!-- /wp:columns -->

    <!-- wp:html -->
    <div class="wp-block-columns">
        <div class="wp-block-column"><a class="stjo-give-tile" href="#"><img src="<?php echo esc_url(stjo_asset('article-person.png')); ?>" alt="" aria-hidden="true"><span class="stjo-give-tile__title">Planned Giving</span><span class="stjo-give-tile__sub">Leave a lasting legacy</span></a></div>
        <div class="wp-block-column"><a class="stjo-give-tile" href="#"><img src="<?php echo esc_url(stjo_asset('directions-car.png')); ?>" alt="" aria-hidden="true"><span class="stjo-give-tile__title">Donate Your Vehicle</span><span class="stjo-give-tile__sub">Turn your car into hope</span></a></div>
        <div class="wp-block-column"><a class="stjo-give-tile" href="#"><img src="<?php echo esc_url(stjo_asset('local-mall.png')); ?>" alt="" aria-hidden="true"><span class="stjo-give-tile__title">Our Shop</span><span class="stjo-give-tile__sub">Shop handmade Lakota crafts</span></a></div>
        <div class="wp-block-column"><a class="stjo-give-tile" href="#"><img src="<?php echo esc_url(stjo_asset('redeem.png')); ?>" alt="" aria-hidden="true"><span class="stjo-give-tile__title">Wishlists &amp; Gift Cards</span><span class="stjo-give-tile__sub">Give specific items students need</span></a></div>
    </div>
    <!-- /wp:html -->

    <!-- wp:spacer {"height":"var:preset|spacing|small"} -->
    <div style="height:var(--wp--preset--spacing--small)" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->

    <!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
    <div class="wp-block-buttons is-layout-flex is-content-justification-center"><!-- wp:button {"backgroundColor":"yellow","textColor":"blue-900"} -->
        <div class="wp-block-button"><a class="wp-block-button__link has-blue-900-color has-text-color has-yellow-background-color has-background wp-element-button" href="#">Donate Now</a></div>
        <!-- /wp:button -->
    </div>
    <!-- /wp:buttons -->

    <!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
    <div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->
</div>
<!-- /wp:group -->