<?php
/**
 * home pattern — generated by figma-to-wp-4.0 registry/render_patterns.py.
 * Regenerate rather than hand-editing; content edits belong in the WP editor
 * after seeding (this file is the seed source, not the live content).
 *
 * @package stjo
 */
?>
<!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'cover.png' ) ); ?>","dimRatio":30,"overlayColor":"blue-900","isUserOverlayColor":true,"minHeight":418,"align":"full","className":"stjo-hero"} -->
<div class="wp-block-cover alignfull stjo-hero" style="min-height:418px"><span aria-hidden="true" class="wp-block-cover__background has-blue-900-background-color has-background-dim-30 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'cover.png' ) ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":1,"textColor":"white"} -->
<h1 class="wp-block-heading has-white-color has-text-color">Become a <strong>DreamMaker</strong></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"white"} -->
<p class="has-white-color has-text-color">The DreamMakers are a special group of friends who give automatic monthly gifts to ensure the Lakota (Sioux) children are provided for year-round… <strong>and will help provide dreams for the future.</strong></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex"}} -->
<div class="wp-block-buttons is-layout-flex"><!-- wp:button {"className":"is-style-fill","textColor":"brand-dark","backgroundColor":"white"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link has-brand-dark-color has-text-color has-white-background-color has-background wp-element-button" href="#">Give Monthly</a></div>
<!-- /wp:button -->
<!-- wp:button {"className":"is-style-fill","textColor":"brand-dark","backgroundColor":"white"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link has-brand-dark-color has-text-color has-white-background-color has-background wp-element-button" href="#">Learn More</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover -->

<!-- wp:separator {"className":"alignfull"} -->
<hr class="wp-block-separator has-alpha-channel-opacity alignfull"/>
<!-- /wp:separator -->

<!-- wp:group {"align":"full","backgroundColor":"light","layout":{"type":"constrained"},"className":"stjo-donation-band"} -->
<div class="wp-block-group alignfull stjo-donation-band has-light-background-color has-background"><!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"verticalAlignment":"center"} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">"Because of you, a child woke up today with somewhere safe to call home."</h2>
<!-- /wp:heading --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:stjo/donation-selector /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","className":"stjo-cards-band","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull stjo-cards-band"><!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->



<!-- wp:heading {"textAlign":"center","level":2} -->
<h2 class="wp-block-heading has-text-align-center">The Culture That <strong>Shapes Every Child</strong></h2>
<!-- /wp:heading -->

<!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'card.png' ) ); ?>","dimRatio":40,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
<div class="wp-block-cover stjo-card" style="min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-40 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'card.png' ) ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
<h3 class="wp-block-heading has-light-color has-text-color">Our Mission</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
<p class="has-light-color has-text-color stjo-card__reveal">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
<div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">See Our Mission</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'card-2.png' ) ); ?>","dimRatio":40,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
<div class="wp-block-cover stjo-card" style="min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-40 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'card-2.png' ) ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
<h3 class="wp-block-heading has-light-color has-text-color">About Our Children</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
<p class="has-light-color has-text-color stjo-card__reveal">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
<div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">Meet Our Children</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'card-3.png' ) ); ?>","dimRatio":40,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
<div class="wp-block-cover stjo-card" style="min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-40 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'card-3.png' ) ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
<h3 class="wp-block-heading has-light-color has-text-color">Our Programs</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
<p class="has-light-color has-text-color stjo-card__reveal">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
<div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">Explore Our Programs</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","backgroundColor":"brand-dark","textColor":"white","layout":{"type":"constrained"},"className":"stjo-video-band"} -->
<div class="wp-block-group alignfull stjo-video-band has-white-color has-brand-dark-background-color has-text-color has-background"><!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:image {"sizeSlug":"large","align":"center","className":"is-style-rounded stjo-video"} -->
<figure class="wp-block-image aligncenter size-large is-style-rounded stjo-video"><img src="<?php echo esc_url( stjo_asset( 'video-placer.png' ) ); ?>" alt="You Can Light a Spark in Every Child!"/></figure>
<!-- /wp:image -->

<!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:heading {"textAlign":"center","level":2,"textColor":"white"} -->
<h2 class="wp-block-heading has-text-align-center has-white-color has-text-color">You Can Light a Spark in Every Child!</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"light"} -->
<p class="has-text-align-center has-light-color has-text-color">For nearly a century, St. Joseph’s has been lighting<strong> The Spark</strong> of curiosity,  energy and promise that lights the way to a brighter future.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons is-layout-flex is-content-justification-center"><!-- wp:button {"className":"is-style-outline","textColor":"white","backgroundColor":"white"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-white-color has-text-color has-white-background-color has-background wp-element-button" href="#">Donate</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->

<!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'columns.png' ) ); ?>","dimRatio":60,"overlayColor":"blue-900","isUserOverlayColor":true,"minHeight":783,"align":"full","className":"stjo-stats"} -->
<div class="wp-block-cover alignfull stjo-stats" style="min-height:783px"><span aria-hidden="true" class="wp-block-cover__background has-blue-900-background-color has-background-dim-60 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'columns.png' ) ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container">

<!-- wp:heading {"textAlign":"center","level":2,"textColor":"light"} -->
<h2 class="wp-block-heading has-text-align-center has-light-color has-text-color">Here's What Happens <strong>When You Give</strong></h2>
<!-- /wp:heading -->

<!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"className":"stjo-stats__row"} -->
<div class="wp-block-columns stjo-stats__row"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","className":"stjo-stat__photo"} -->
<figure class="wp-block-image aligncenter stjo-stat__photo"><img src="<?php echo esc_url( stjo_asset( 'ellipse-4.png' ) ); ?>" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","className":"stjo-stat__figure"} -->
<p class="has-text-align-center stjo-stat__figure">22,610</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"center","level":3,"textColor":"white"} -->
<h3 class="wp-block-heading has-text-align-center has-white-color has-text-color">Free Books</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"light","className":"stjo-stat__label"} -->
<p class="has-text-align-center has-light-color has-text-color stjo-stat__label">were given to 1,300 adults and youth in reservation communities</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","className":"stjo-stat__photo"} -->
<figure class="wp-block-image aligncenter stjo-stat__photo"><img src="<?php echo esc_url( stjo_asset( 'ellipse-4-2.png' ) ); ?>" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","className":"stjo-stat__figure"} -->
<p class="has-text-align-center stjo-stat__figure">$275,000</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"center","level":3,"textColor":"white"} -->
<h3 class="wp-block-heading has-text-align-center has-white-color has-text-color">Was awarded</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"light","className":"stjo-stat__label"} -->
<p class="has-text-align-center has-light-color has-text-color stjo-stat__label">to Native American students  pursuing higher education</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","className":"stjo-stat__photo"} -->
<figure class="wp-block-image aligncenter stjo-stat__photo"><img src="<?php echo esc_url( stjo_asset( 'ellipse-4-3.png' ) ); ?>" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","className":"stjo-stat__figure"} -->
<p class="has-text-align-center stjo-stat__figure">24,274</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"center","level":3,"textColor":"white"} -->
<h3 class="wp-block-heading has-text-align-center has-white-color has-text-color">Meals</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"light","className":"stjo-stat__label"} -->
<p class="has-text-align-center has-light-color has-text-color stjo-stat__label">were given to 1,300 adults and youth in reservation communities</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","className":"stjo-stat__photo"} -->
<figure class="wp-block-image aligncenter stjo-stat__photo"><img src="<?php echo esc_url( stjo_asset( 'ellipse-4-4.png' ) ); ?>" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","className":"stjo-stat__figure"} -->
<p class="has-text-align-center stjo-stat__figure">3,707</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"center","level":3,"textColor":"white"} -->
<h3 class="wp-block-heading has-text-align-center has-white-color has-text-color">Medical visits</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"light","className":"stjo-stat__label"} -->
<p class="has-text-align-center has-light-color has-text-color stjo-stat__label">took place in our campus  health center</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons is-layout-flex is-content-justification-center"><!-- wp:button {"className":"is-style-fill"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link wp-element-button" href="#">Your Impact</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover -->

<!-- wp:group {"align":"full","className":"stjo-blog-band","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull stjo-blog-band"><!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->



<!-- wp:columns {"verticalAlignment":"center"} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center","width":"70%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:70%"><!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Stories from <strong>St. Joseph's</strong></h2>
<!-- /wp:heading --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"30%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:30%"><!-- wp:buttons {"layout":{"type":"flex","justifyContent":"right"}} -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-arrow-link"} -->
<div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link wp-element-button" href="/blog/">View All</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:query {"queryId":1,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","inherit":false},"className":"stjo-blog-grid"} -->
<div class="wp-block-query stjo-blog-grid"><!-- wp:post-template {"layout":{"type":"grid","columnCount":3}} -->
<!-- wp:post-featured-image {"isLink":true,"aspectRatio":"4/3","className":"is-style-rounded"} /-->

<!-- wp:post-title {"isLink":true,"level":3} /-->

<!-- wp:post-excerpt {"excerptLength":24} /-->

<!-- wp:read-more {"content":"Read More"} /-->
<!-- /wp:post-template --></div>
<!-- /wp:query -->

<!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->

<!-- wp:separator {"className":"alignfull"} -->
<hr class="wp-block-separator has-alpha-channel-opacity alignfull"/>
<!-- /wp:separator -->

<!-- wp:group {"align":"full","className":"stjo-generosity","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull stjo-generosity"><!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:heading {"textAlign":"center","level":2,"textColor":"white"} -->
<h2 class="wp-block-heading has-text-align-center has-white-color has-text-color">Your Generosity  <strong>Changes Everything</strong></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"light"} -->
<p class="has-text-align-center has-light-color has-text-color">Every gift, no matter the size or how you give, brings hope, culture, and opportunity to a Lakota child at St. Joseph's.</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":"var:preset|spacing|small"} -->
<div style="height:var(--wp--preset--spacing--small)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'card-4.png' ) ); ?>","dimRatio":50,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
<div class="wp-block-cover stjo-card" style="min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'card-4.png' ) ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
<h3 class="wp-block-heading has-light-color has-text-color">Monthly giving</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
<p class="has-light-color has-text-color stjo-card__reveal">Be a DreamMaker with a recurring gift</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
<div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">Give Monthly Now</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'card-5.png' ) ); ?>","dimRatio":50,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
<div class="wp-block-cover stjo-card" style="min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'card-5.png' ) ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
<h3 class="wp-block-heading has-light-color has-text-color">One-Time Gift</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
<p class="has-light-color has-text-color stjo-card__reveal">Make an immediate impact today</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
<div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">Give Now</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'card-6.png' ) ); ?>","dimRatio":50,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
<div class="wp-block-cover stjo-card" style="min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'card-6.png' ) ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
<h3 class="wp-block-heading has-light-color has-text-color">Donor  Advised Fund</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
<p class="has-light-color has-text-color stjo-card__reveal">Give through your DAF account</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
<div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">Give Now</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'card-7.png' ) ); ?>","dimRatio":50,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
<div class="wp-block-cover stjo-card" style="min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'card-7.png' ) ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
<h3 class="wp-block-heading has-light-color has-text-color">Memorial Gift</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
<p class="has-light-color has-text-color stjo-card__reveal">Honor a loved one's memory</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
<div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">Give Now</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->

<!-- wp:html -->
<div class="wp-block-columns"><div class="wp-block-column"><a class="stjo-give-tile" href="#"><img src="<?php echo esc_url( stjo_asset( 'article-person.png' ) ); ?>" alt="" aria-hidden="true"><span class="stjo-give-tile__title">Planned Giving</span><span class="stjo-give-tile__sub">Leave a lasting legacy</span></a></div><div class="wp-block-column"><a class="stjo-give-tile" href="#"><img src="<?php echo esc_url( stjo_asset( 'directions-car.png' ) ); ?>" alt="" aria-hidden="true"><span class="stjo-give-tile__title">Donate Your Vehicle</span><span class="stjo-give-tile__sub">Turn your car into hope</span></a></div><div class="wp-block-column"><a class="stjo-give-tile" href="#"><img src="<?php echo esc_url( stjo_asset( 'local-mall.png' ) ); ?>" alt="" aria-hidden="true"><span class="stjo-give-tile__title">Our Shop</span><span class="stjo-give-tile__sub">Shop handmade Lakota crafts</span></a></div><div class="wp-block-column"><a class="stjo-give-tile" href="#"><img src="<?php echo esc_url( stjo_asset( 'redeem.png' ) ); ?>" alt="" aria-hidden="true"><span class="stjo-give-tile__title">Wishlists &amp; Gift Cards</span><span class="stjo-give-tile__sub">Give specific items students need</span></a></div></div>
<!-- /wp:html -->

<!-- wp:spacer {"height":"var:preset|spacing|small"} -->
<div style="height:var(--wp--preset--spacing--small)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons is-layout-flex is-content-justification-center"><!-- wp:button {"backgroundColor":"yellow","textColor":"blue-900"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-blue-900-color has-text-color has-yellow-background-color has-background wp-element-button" href="#">Donate Now</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","backgroundColor":"blue-900","className":"stjo-testimonial-band","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull stjo-testimonial-band has-blue-900-background-color has-background"><!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:group {"className":"stjo-testimonial stjo-testimonial--on-dark","layout":{"type":"constrained","contentSize":"768px"}} -->
<div class="wp-block-group stjo-testimonial stjo-testimonial--on-dark">

<!-- wp:paragraph {"align":"center","className":"stjo-testimonial__quote"} -->
<p class="has-text-align-center stjo-testimonial__quote">“My husband and I are happy to contribute to St. Joseph’s School children. We give 3 or 4 times a year, and send email Valentines each February. I’ve spoken to a staff member on the phone, received personal voice messages of thanks, as well as Thank You’s from the children. If you read some of the negative reviews, just remember that some people will complain no matter what! St. Joseph’s doesn’t need their negativity or their money. We believe our financial support is going to GREAT people who have an even GREATER need than many nonprofits. We believe in you and thank you for all you do!!”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","fontSize":"small"} -->
<p class="has-text-align-center has-small-font-size">User: Rrcmbec4077</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons is-layout-flex is-content-justification-center"><!-- wp:button {"backgroundColor":"yellow","textColor":"blue-900"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-blue-900-color has-text-color has-yellow-background-color has-background wp-element-button" href="#">Share Your Story</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->
