<?php
/**
 * Block pattern category + section pattern loader.
 * Every file in inc/patterns/ is ONE structural section pattern (hero band,
 * n-column cards...) generated by registry/render_patterns.py. Page seeds live
 * in inc/page-content/ and are NOT registered as patterns.
 *
 * Pattern files may carry a header comment:
 *   Title: 3-Column Cover Cards
 *   Description: Structure: card-trio. Source: home — About Us band.
 *
 * @package stjo
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Register the pattern category (theme name).
 */
function stjo_register_pattern_category() {
	register_block_pattern_category( 'stjo', array(
		'label' => wp_get_theme()->get( 'Name' ),
	) );
}
add_action( 'init', 'stjo_register_pattern_category' );

/**
 * Register each inc/patterns/*.php file as a block pattern.
 */
function stjo_register_patterns() {
	$dir = get_template_directory() . '/inc/patterns/';
	if ( ! is_dir( $dir ) ) {
		return;
	}
	foreach ( glob( $dir . '*.php' ) as $file ) {
		$headers = get_file_data( $file, array(
			'title'       => 'Title',
			'description' => 'Description',
		) );
		$slug  = 'stjo/' . basename( $file, '.php' );
		$title = $headers['title'] ?: ucwords( str_replace( '-', ' ', basename( $file, '.php' ) ) );
		ob_start();
		include $file;
		$content = ob_get_clean();
		register_block_pattern( $slug, array(
			'title'       => $title,
			'description' => $headers['description'],
			'categories'  => array( 'stjo' ),
			'content'     => trim( $content ),
			'inserter'    => true,
		) );
	}
}
add_action( 'init', 'stjo_register_patterns' );
