<?php
/**
 * CPT: Student Story — generated by figma-to-wp-4.0 setup/cpt_scaffold.py.
 * Auto-loaded by inc/cpt-loader.php.
 *
 * @package stjo
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

function stjo_register_student_story() {
	register_post_type( 'student-story', array(
		'labels'       => array(
			'name'          => __( 'Student Stories', 'stjo' ),
			'singular_name' => __( 'Student Story', 'stjo' ),
			'add_new_item'  => __( 'Add New Student Story', 'stjo' ),
			'edit_item'     => __( 'Edit Student Story', 'stjo' ),
		),
		'public'       => true,
		'show_in_rest' => true,
		'menu_icon'    => 'dashicons-groups',
		'supports'     => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
		'has_archive'  => 'student-stories',
		'rewrite'      => array( 'slug' => 'student-stories', 'with_front' => false ),
	) );
}
add_action( 'init', 'stjo_register_student_story' );
