<?php
/**
 * CPT: Student Story — generated by figma-to-wp-4.0 setup/cpt_scaffold.py.
 * Auto-loaded by inc/cpt-loader.php.
 *
 * @package stjo
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

function stjo_register_student_story() {
	register_post_type( 'student-story', array(
		'labels'       => array(
			'name'          => __( 'Student Stories', 'stjo' ),
			'singular_name' => __( 'Student Story', 'stjo' ),
			'add_new_item'  => __( 'Add New Student Story', 'stjo' ),
			'edit_item'     => __( 'Edit Student Story', 'stjo' ),
		),
		'public'       => true,
		'show_in_rest' => true,
		'menu_icon'    => 'dashicons-groups',
		'supports'     => array( 'title', 'editor', 'thumbnail', 'excerpt', 'custom-fields' ), // custom-fields: REST meta for the image-focus panel
		// No auto-archive: the /student-stories/ page (built from stjo/stories-section
		// blocks) is the archive now. Singles live under /student-story/ (singular)
		// so they don't collide with that page's URL.
		'has_archive'  => false,
		'rewrite'      => array( 'slug' => 'student-story', 'with_front' => false ),
	) );

	// Category drives which archive section a story renders in (Student
	// Stories vs the two Graduates sections vs Alumni, per the design); Year
	// powers the archive's filter pills. (A separate Story Tag taxonomy was
	// removed 2026-08-07 — it duplicated the grade-level categories.)
	register_taxonomy( 'story-category', 'student-story', array(
		'labels'            => array(
			'name'          => __( 'Story Categories', 'stjo' ),
			'singular_name' => __( 'Story Category', 'stjo' ),
		),
		'hierarchical'      => true,
		'public'            => false,
		'show_ui'           => true,
		'show_in_rest'      => true,
		'show_admin_column' => true,
		'rewrite'           => false,
	) );

	// "Class Year" = the graduating class year; used by the Graduates sections.
	register_taxonomy( 'story-year', 'student-story', array(
		'labels'            => array(
			'name'          => __( 'Class Year', 'stjo' ),
			'singular_name' => __( 'Class Year', 'stjo' ),
		),
		'hierarchical'      => false,
		'public'            => false,
		'show_ui'           => true,
		'show_in_rest'      => true,
		'show_admin_column' => true,
		'rewrite'           => false,
	) );
}
add_action( 'init', 'stjo_register_student_story' );

/**
 * Card/lightbox image focus, stored as a CSS object-position value ("X% Y%")
 * from the editor's FocalPointPicker panel (assets/js/story-focus-panel.js).
 * Lets editors position each photo within its fixed-height card crop.
 */
function stjo_story_sanitize_focus( $value ) {
	$parts = preg_split( '/\s+/', trim( (string) $value ) );
	if ( 2 === count( $parts )
		&& preg_match( '/^(\d{1,3}(?:\.\d+)?)%$/', $parts[0], $mx )
		&& preg_match( '/^(\d{1,3}(?:\.\d+)?)%$/', $parts[1], $my ) ) {
		$x = min( 100, max( 0, (float) $mx[1] ) );
		$y = min( 100, max( 0, (float) $my[1] ) );
		return $x . '% ' . $y . '%';
	}
	return 'center center';
}

function stjo_story_register_meta() {
	register_post_meta( 'student-story', 'stjo_story_image_focus', array(
		'type'              => 'string',
		'single'            => true,
		'default'           => 'center center',
		'sanitize_callback' => 'stjo_story_sanitize_focus',
		'show_in_rest'      => true,
		'auth_callback'     => function () {
			return current_user_can( 'edit_posts' );
		},
	) );
}
add_action( 'init', 'stjo_story_register_meta' );

/**
 * FocalPointPicker panel (block editor sidebar) for the focus meta.
 */
function stjo_story_editor_assets() {
	$screen = function_exists( 'get_current_screen' ) ? get_current_screen() : null;
	if ( ! $screen || 'student-story' !== $screen->post_type ) {
		return;
	}
	wp_enqueue_script(
		'stjo-story-focus-panel',
		get_template_directory_uri() . '/assets/js/story-focus-panel.js',
		array( 'wp-plugins', 'wp-editor', 'wp-edit-post', 'wp-components', 'wp-element', 'wp-data' ),
		(string) filemtime( get_template_directory() . '/assets/js/story-focus-panel.js' ), // mtime version: stale copies stick in the editor on STJO_VERSION
		true
	);
}
add_action( 'enqueue_block_editor_assets', 'stjo_story_editor_assets' );

/**
 * Breadcrumbs: Student Stories lives under About in the site structure
 * (Home > About > Student Stories per the design), but the CPT archive has
 * no real page ancestor, so splice the About page in after Home on the
 * archive and on single stories.
 */
function stjo_student_story_breadcrumbs( $links ) {
	if ( ! is_post_type_archive( 'student-story' ) && ! is_singular( 'student-story' ) ) {
		return $links;
	}
	$about = get_page_by_path( 'about' );
	if ( ! $about || ! is_array( $links ) ) {
		return $links;
	}
	array_splice( $links, 1, 0, array(
		array(
			'url'  => get_permalink( $about ),
			'text' => get_the_title( $about ),
		),
	) );
	return $links;
}
add_filter( 'wpseo_breadcrumb_links', 'stjo_student_story_breadcrumbs' );
