<?php
/**
 * Theme config loader. Client-specific content (nav fallback, footer contact,
 * social links, newsletter copy, legal line, header CTAs) lives in
 * theme-config.json at the theme root — generated by the build from the
 * project build-spec — so template parts stay generic.
 *
 * @package stjo
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Full config array (cached). Missing file or keys fall back to safe defaults.
 */
function stjo_config() {
	static $config = null;
	if ( null !== $config ) {
		return $config;
	}
	$defaults = array(
		'header' => array(
			'ctas'          => array(
				array( 'label' => 'Donate', 'url' => '/donate/', 'style' => 'primary' ),
			),
			'menu_fallback' => array(),
			'show_search'   => true,
		),
		'footer' => array(
			'tagline'     => '',
			'contact'     => array(),   // items: { icon: address|phone|email, text, url? }
			'links'       => array(),   // fallback footer menu: { label, url }
			'social'      => array(),   // items: { network, url, icon? (attachment/asset path) }
			'newsletter'  => array( 'heading' => '', 'body' => '', 'action' => '' ),
			'partners'    => array(),   // items: { name, image, url? }
			'legal'       => '',
			'privacy_url' => '/privacy-policy/',
		),
	);
	$file = get_template_directory() . '/theme-config.json';
	$data = array();
	if ( file_exists( $file ) ) {
		$decoded = json_decode( (string) file_get_contents( $file ), true );
		if ( is_array( $decoded ) ) {
			$data = $decoded;
		}
	}
	$config = array_replace_recursive( $defaults, $data );
	return $config;
}

/**
 * Dot-path getter: stjo_config_get( 'footer.legal', 'fallback' ).
 */
function stjo_config_get( $path, $fallback = '' ) {
	$value = stjo_config();
	foreach ( explode( '.', $path ) as $key ) {
		if ( ! is_array( $value ) || ! array_key_exists( $key, $value ) ) {
			return $fallback;
		}
		$value = $value[ $key ];
	}
	return $value;
}
