<?php
/**
 * Title: 3-Column Cover Cards
 * Categories: cards
 * Description: Structure: card-trio. Source: home — Culture cards (About Us trio). Generated by render_patterns.py.
 *
 * @package stjo
 */
?>
<!-- wp:group {"metadata":{"name":"3-Column Cover Cards"},"align":"full","className":"stjo-cards-band","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull stjo-cards-band"><!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->



<!-- wp:heading {"textAlign":"center","level":2} -->
<h2 class="wp-block-heading has-text-align-center">The Culture That <strong>Shapes Every Child</strong></h2>
<!-- /wp:heading -->

<!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'card.png' ) ); ?>","dimRatio":40,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
<div class="wp-block-cover stjo-card" style="min-height:400px"><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'card.png' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-40 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
<h3 class="wp-block-heading has-light-color has-text-color">Our Mission</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
<p class="has-light-color has-text-color stjo-card__reveal">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
<div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">See Our Mission</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'card-2.png' ) ); ?>","dimRatio":40,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
<div class="wp-block-cover stjo-card" style="min-height:400px"><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'card-2.png' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-40 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
<h3 class="wp-block-heading has-light-color has-text-color">About Our Children</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
<p class="has-light-color has-text-color stjo-card__reveal">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
<div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">Meet Our Children</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'card-3.png' ) ); ?>","dimRatio":40,"overlayColor":"black","minHeight":400,"className":"stjo-card"} -->
<div class="wp-block-cover stjo-card" style="min-height:400px"><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'card-3.png' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-40 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
<h3 class="wp-block-heading has-light-color has-text-color">Our Programs</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
<p class="has-light-color has-text-color stjo-card__reveal">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
<div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="#">Explore Our Programs</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->
