<?php
/**
 * Title: 4-Column Stats on Photo Band
 * Categories: stats
 * Description: Structure: impact-stats. Source: home — Columns. Generated by render_patterns.py.
 *
 * @package stjo
 */
?>
<!-- wp:cover {"metadata":{"name":"4-Column Stats on Photo Band"},"url":"<?php echo esc_url( stjo_asset( 'columns.png' ) ); ?>","dimRatio":60,"overlayColor":"blue-900","isUserOverlayColor":true,"minHeight":783,"align":"full","className":"stjo-stats"} -->
<div class="wp-block-cover alignfull stjo-stats" style="min-height:783px"><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'columns.png' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-blue-900-background-color has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">

<!-- wp:heading {"textAlign":"center","level":2,"textColor":"light"} -->
<h2 class="wp-block-heading has-text-align-center has-light-color has-text-color">Here's What Happens <strong>When You Give</strong></h2>
<!-- /wp:heading -->

<!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"className":"stjo-stats__row"} -->
<div class="wp-block-columns stjo-stats__row"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","className":"stjo-stat__photo"} -->
<figure class="wp-block-image aligncenter stjo-stat__photo"><img src="<?php echo esc_url( stjo_asset( 'ellipse-4.png' ) ); ?>" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","className":"stjo-stat__figure"} -->
<p class="has-text-align-center stjo-stat__figure">22,610</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"center","level":3,"textColor":"white"} -->
<h3 class="wp-block-heading has-text-align-center has-white-color has-text-color">Free Books</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"light","className":"stjo-stat__label"} -->
<p class="has-text-align-center has-light-color has-text-color stjo-stat__label">were given to 1,300 adults and youth in reservation communities</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","className":"stjo-stat__photo"} -->
<figure class="wp-block-image aligncenter stjo-stat__photo"><img src="<?php echo esc_url( stjo_asset( 'ellipse-4-2.png' ) ); ?>" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","className":"stjo-stat__figure"} -->
<p class="has-text-align-center stjo-stat__figure">$275,000</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"center","level":3,"textColor":"white"} -->
<h3 class="wp-block-heading has-text-align-center has-white-color has-text-color">Was awarded</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"light","className":"stjo-stat__label"} -->
<p class="has-text-align-center has-light-color has-text-color stjo-stat__label">to Native American students  pursuing higher education</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","className":"stjo-stat__photo"} -->
<figure class="wp-block-image aligncenter stjo-stat__photo"><img src="<?php echo esc_url( stjo_asset( 'ellipse-4-3.png' ) ); ?>" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","className":"stjo-stat__figure"} -->
<p class="has-text-align-center stjo-stat__figure">24,274</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"center","level":3,"textColor":"white"} -->
<h3 class="wp-block-heading has-text-align-center has-white-color has-text-color">Meals</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"light","className":"stjo-stat__label"} -->
<p class="has-text-align-center has-light-color has-text-color stjo-stat__label">were given to 1,300 adults and youth in reservation communities</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","className":"stjo-stat__photo"} -->
<figure class="wp-block-image aligncenter stjo-stat__photo"><img src="<?php echo esc_url( stjo_asset( 'ellipse-4-4.png' ) ); ?>" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","className":"stjo-stat__figure"} -->
<p class="has-text-align-center stjo-stat__figure">3,707</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"center","level":3,"textColor":"white"} -->
<h3 class="wp-block-heading has-text-align-center has-white-color has-text-color">Medical visits</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"light","className":"stjo-stat__label"} -->
<p class="has-text-align-center has-light-color has-text-color stjo-stat__label">took place in our campus  health center</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons is-layout-flex is-content-justification-center"><!-- wp:button {"className":"is-style-fill"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link wp-element-button" href="#">Your Impact</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover -->
