<?php
/**
 * Title: Band: Centered Testimonial
 * Description: Structure: testimonial. Source: home — Ways to Give. Generated by render_patterns.py.
 *
 * @package stjo
 */
?>
<!-- wp:group {"metadata":{"name":"Band: Centered Testimonial"},"align":"full","backgroundColor":"blue-900","className":"stjo-testimonial-band","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull stjo-testimonial-band has-blue-900-background-color has-background"><!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:group {"className":"stjo-testimonial stjo-testimonial--on-dark","layout":{"type":"constrained","contentSize":"768px"}} -->
<div class="wp-block-group stjo-testimonial stjo-testimonial--on-dark">

<!-- wp:paragraph {"align":"center","className":"stjo-testimonial__quote"} -->
<p class="has-text-align-center stjo-testimonial__quote">“My husband and I are happy to contribute to St. Joseph’s School children. We give 3 or 4 times a year, and send email Valentines each February. I’ve spoken to a staff member on the phone, received personal voice messages of thanks, as well as Thank You’s from the children. If you read some of the negative reviews, just remember that some people will complain no matter what! St. Joseph’s doesn’t need their negativity or their money. We believe our financial support is going to GREAT people who have an even GREATER need than many nonprofits. We believe in you and thank you for all you do!!”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","fontSize":"small"} -->
<p class="has-text-align-center has-small-font-size">User: Rrcmbec4077</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons is-layout-flex is-content-justification-center"><!-- wp:button {"backgroundColor":"yellow","textColor":"blue-900"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-blue-900-color has-text-color has-yellow-background-color has-background wp-element-button" href="#">Share Your Story</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->
