<?php
/**
 * Title: Band: Video + CTA
 * Description: Structure: video-band. Source: home — Video. Generated by render_patterns.py.
 *
 * @package stjo
 */
?>
<!-- wp:group {"align":"full","backgroundColor":"brand-dark","textColor":"white","layout":{"type":"constrained"},"className":"stjo-video-band"} -->
<div class="wp-block-group alignfull stjo-video-band has-white-color has-brand-dark-background-color has-text-color has-background"><!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:image {"sizeSlug":"large","align":"center","className":"is-style-rounded stjo-video"} -->
<figure class="wp-block-image aligncenter size-large is-style-rounded stjo-video"><img src="<?php echo esc_url( stjo_asset( 'video-placer.png' ) ); ?>" alt="You Can Light a Spark in Every Child!"/></figure>
<!-- /wp:image -->

<!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
<div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:heading {"textAlign":"center","level":2,"textColor":"white"} -->
<h2 class="wp-block-heading has-text-align-center has-white-color has-text-color">You Can Light a Spark in Every Child!</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"light"} -->
<p class="has-text-align-center has-light-color has-text-color">For nearly a century, St. Joseph’s has been lighting<strong> The Spark</strong> of curiosity,  energy and promise that lights the way to a brighter future.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons is-layout-flex is-content-justification-center"><!-- wp:button {"className":"is-style-outline","textColor":"white","backgroundColor":"white"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-white-color has-text-color has-white-background-color has-background wp-element-button" href="#">Donate</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->
