<?php

/**
 * Title: Band: Photo Cards + Icon Tiles + CTA
 * Categories: cards
 * Description: Structure: generosity. Source: home — Your Generosity band (intro + photo cards + tiles + donate). Generated by render_patterns.py.
 *
 * Links come from theme-config.json give.* so this pattern and the site-wide
 * pre-footer (template-parts/global/pre-footer.php, the same band) never
 * disagree about where a way to give points.
 *
 * @package stjo
 */

$stjo_give_once     = esc_url( stjo_config_get( 'give.once_url', 'https://give.stjo.org/site/Donation2?df_id=6740&6740.donation=form1' ) );
$stjo_give_monthly  = esc_url( stjo_config_get( 'give.monthly_url', $stjo_give_once ) );
$stjo_give_daf      = esc_url( stjo_config_get( 'give.daf_url', $stjo_give_once ) );
$stjo_give_memorial = esc_url( stjo_config_get( 'give.memorial_url', $stjo_give_once ) );
$stjo_give_planned  = esc_url( stjo_config_get( 'give.planned_url', '/support-us/planned-giving/' ) );
$stjo_give_vehicle  = esc_url( stjo_config_get( 'give.vehicle_url', '/support-us/donate-your-vehicle/' ) );
$stjo_give_shop     = esc_url( stjo_config_get( 'give.shop_url', '/support-us/our-shop/' ) );
$stjo_give_wishlist = esc_url( stjo_config_get( 'give.wishlists_url', '/support-us/wishlists-gift-cards/' ) );
?>
<!-- wp:group {"metadata":{"name":"Band: Photo Cards + Icon Tiles + CTA"},"align":"full","className":"stjo-generosity","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull stjo-generosity"><!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
    <div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->

    <!-- wp:heading {"textAlign":"center","level":2,"textColor":"white"} -->
    <h2 class="wp-block-heading has-text-align-center has-white-color has-text-color">Your Generosity <strong>Changes Everything</strong></h2>
    <!-- /wp:heading -->

    <!-- wp:paragraph {"align":"center","textColor":"light"} -->
    <p class="has-text-align-center has-light-color has-text-color">Every gift, no matter the size or how you give, brings hope, culture, and opportunity to a Lakota child at St. Joseph's.</p>
    <!-- /wp:paragraph -->

    <!-- wp:spacer {"height":"var:preset|spacing|small"} -->
    <div style="height:var(--wp--preset--spacing--small)" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->

    <!-- wp:columns {"align":"wide","className":"stjo-give-row"} -->
    <div class="wp-block-columns alignwide stjo-give-row"><!-- wp:column -->
        <div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url(stjo_asset('card-4.png')); ?>","dimRatio":50,"overlayColor":"black","minHeight":340,"className":"stjo-card"} -->
            <div class="wp-block-cover stjo-card" style="min-height:340px"><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url(stjo_asset('card-4.png')); ?>" data-object-fit="cover" /><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span>
                <div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
                    <h3 class="wp-block-heading has-light-color has-text-color">Monthly giving</h3>
                    <!-- /wp:heading -->

                    <!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
                    <p class="has-light-color has-text-color stjo-card__reveal">Be a DreamMaker with a recurring gift</p>
                    <!-- /wp:paragraph -->

                    <!-- wp:buttons -->
                    <div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
                        <div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="<?php echo $stjo_give_monthly; ?>">Give Monthly Now</a></div>
                        <!-- /wp:button -->
                    </div>
                    <!-- /wp:buttons -->
                </div>
            </div>
            <!-- /wp:cover -->
        </div>
        <!-- /wp:column -->
        <!-- wp:column -->
        <div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url(stjo_asset('card-5.png')); ?>","dimRatio":50,"overlayColor":"black","minHeight":340,"className":"stjo-card"} -->
            <div class="wp-block-cover stjo-card" style="min-height:340px"><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url(stjo_asset('card-5.png')); ?>" data-object-fit="cover" /><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span>
                <div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
                    <h3 class="wp-block-heading has-light-color has-text-color">One-Time Gift</h3>
                    <!-- /wp:heading -->

                    <!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
                    <p class="has-light-color has-text-color stjo-card__reveal">Make an immediate impact today</p>
                    <!-- /wp:paragraph -->

                    <!-- wp:buttons -->
                    <div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
                        <div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="<?php echo $stjo_give_once; ?>">Give Now</a></div>
                        <!-- /wp:button -->
                    </div>
                    <!-- /wp:buttons -->
                </div>
            </div>
            <!-- /wp:cover -->
        </div>
        <!-- /wp:column -->
        <!-- wp:column -->
        <div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url(stjo_asset('card-6.png')); ?>","dimRatio":50,"overlayColor":"black","minHeight":340,"className":"stjo-card"} -->
            <div class="wp-block-cover stjo-card" style="min-height:340px"><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url(stjo_asset('card-6.png')); ?>" data-object-fit="cover" /><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span>
                <div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
                    <h3 class="wp-block-heading has-light-color has-text-color">Donor Advised Fund</h3>
                    <!-- /wp:heading -->

                    <!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
                    <p class="has-light-color has-text-color stjo-card__reveal">Give through your DAF account</p>
                    <!-- /wp:paragraph -->

                    <!-- wp:buttons -->
                    <div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
                        <div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="<?php echo $stjo_give_daf; ?>">Give Now</a></div>
                        <!-- /wp:button -->
                    </div>
                    <!-- /wp:buttons -->
                </div>
            </div>
            <!-- /wp:cover -->
        </div>
        <!-- /wp:column -->
        <!-- wp:column -->
        <div class="wp-block-column"><!-- wp:cover {"url":"<?php echo esc_url(stjo_asset('card-7.png')); ?>","dimRatio":50,"overlayColor":"black","minHeight":340,"className":"stjo-card"} -->
            <div class="wp-block-cover stjo-card" style="min-height:340px"><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url(stjo_asset('card-7.png')); ?>" data-object-fit="cover" /><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span>
                <div class="wp-block-cover__inner-container"><!-- wp:heading {"level":3,"textColor":"light"} -->
                    <h3 class="wp-block-heading has-light-color has-text-color">Memorial Gift</h3>
                    <!-- /wp:heading -->

                    <!-- wp:paragraph {"textColor":"light","className":"stjo-card__reveal"} -->
                    <p class="has-light-color has-text-color stjo-card__reveal">Honor a loved one's memory</p>
                    <!-- /wp:paragraph -->

                    <!-- wp:buttons -->
                    <div class="wp-block-buttons"><!-- wp:button {"textColor":"white","className":"is-style-arrow-link"} -->
                        <div class="wp-block-button is-style-arrow-link"><a class="wp-block-button__link has-white-color has-text-color wp-element-button" href="<?php echo $stjo_give_memorial; ?>">Give Now</a></div>
                        <!-- /wp:button -->
                    </div>
                    <!-- /wp:buttons -->
                </div>
            </div>
            <!-- /wp:cover -->
        </div>
        <!-- /wp:column -->
    </div>
    <!-- /wp:columns -->

    <!-- wp:html -->
    <div class="wp-block-columns alignwide stjo-give-row">
        <div class="wp-block-column"><a class="stjo-give-tile" href="<?php echo $stjo_give_planned; ?>"><img src="<?php echo esc_url(stjo_asset('article-person.png')); ?>" alt="" aria-hidden="true" class="skip-lazy"><span class="stjo-give-tile__title">Planned Giving</span><span class="stjo-give-tile__sub">Leave a lasting legacy</span></a></div>
        <div class="wp-block-column"><a class="stjo-give-tile" href="<?php echo $stjo_give_vehicle; ?>"><img src="<?php echo esc_url(stjo_asset('directions-car.png')); ?>" alt="" aria-hidden="true" class="skip-lazy"><span class="stjo-give-tile__title">Donate Your Vehicle</span><span class="stjo-give-tile__sub">Turn your car into hope</span></a></div>
        <div class="wp-block-column"><a class="stjo-give-tile" href="<?php echo $stjo_give_shop; ?>"><img src="<?php echo esc_url(stjo_asset('local-mall.png')); ?>" alt="" aria-hidden="true" class="skip-lazy"><span class="stjo-give-tile__title">Our Shop</span><span class="stjo-give-tile__sub">Shop handmade Lakota crafts</span></a></div>
        <div class="wp-block-column"><a class="stjo-give-tile" href="<?php echo $stjo_give_wishlist; ?>"><img src="<?php echo esc_url(stjo_asset('redeem.png')); ?>" alt="" aria-hidden="true" class="skip-lazy"><span class="stjo-give-tile__title">Wishlists &amp; Gift Cards</span><span class="stjo-give-tile__sub">Give specific items students need</span></a></div>
    </div>
    <!-- /wp:html -->

    <!-- wp:spacer {"height":"var:preset|spacing|small"} -->
    <div style="height:var(--wp--preset--spacing--small)" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->

    <!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
    <div class="wp-block-buttons is-layout-flex is-content-justification-center"><!-- wp:button {"backgroundColor":"yellow","textColor":"blue-900"} -->
        <div class="wp-block-button"><a class="wp-block-button__link has-blue-900-color has-text-color has-yellow-background-color has-background wp-element-button" href="<?php echo $stjo_give_once; ?>">Donate Now</a></div>
        <!-- /wp:button -->
    </div>
    <!-- /wp:buttons -->

    <!-- wp:spacer {"height":"var:preset|spacing|medium"} -->
    <div style="height:var(--wp--preset--spacing--medium)" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->
</div>
<!-- /wp:group -->