<?php
/**
 * Title: Divider: Zigzag Ribbon
 * Description: Structure: zigzag. Source: home — Separator. Generated by render_patterns.py.
 *
 * @package stjo
 */
?>
<!-- wp:separator {"className":"alignfull"} -->
<hr class="wp-block-separator has-alpha-channel-opacity alignfull"/>
<!-- /wp:separator -->
