<?php
/**
 * Title: Hero: Full-bleed Cover
 * Description: Structure: cover-hero. Source: home — Cover. Generated by render_patterns.py.
 *
 * @package stjo
 */
?>
<!-- wp:cover {"url":"<?php echo esc_url( stjo_asset( 'cover.png' ) ); ?>","dimRatio":30,"overlayColor":"blue-900","isUserOverlayColor":true,"minHeight":418,"align":"full","className":"stjo-hero"} -->
<div class="wp-block-cover alignfull stjo-hero" style="min-height:418px"><span aria-hidden="true" class="wp-block-cover__background has-blue-900-background-color has-background-dim-30 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( stjo_asset( 'cover.png' ) ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":1,"textColor":"white"} -->
<h1 class="wp-block-heading has-white-color has-text-color">Become a <strong>DreamMaker</strong></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"white"} -->
<p class="has-white-color has-text-color">The DreamMakers are a special group of friends who give automatic monthly gifts to ensure the Lakota (Sioux) children are provided for year-round… <strong>and will help provide dreams for the future.</strong></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex"}} -->
<div class="wp-block-buttons is-layout-flex"><!-- wp:button {"className":"is-style-fill","textColor":"brand-dark","backgroundColor":"white"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link has-brand-dark-color has-text-color has-white-background-color has-background wp-element-button" href="#">Give Monthly</a></div>
<!-- /wp:button -->
<!-- wp:button {"className":"is-style-fill","textColor":"brand-dark","backgroundColor":"white"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link has-brand-dark-color has-text-color has-white-background-color has-background wp-element-button" href="#">Learn More</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover -->
