<?php
/**
 * section-landing pattern — generated by figma-to-wp-4.0 registry/render_patterns.py.
 * Regenerate rather than hand-editing; content edits belong in the WP editor
 * after seeding (this file is the seed source, not the live content).
 *
 * @package stjo
 */
$img = get_template_directory_uri() . '/assets/images';
?>
<!-- UNMATCHED SECTION: 'Hero' (Figma 4948:1625) — generic render; review + consider a registry template -->
<!-- wp:cover {"align":"full","dimRatio":60} -->
<div class="wp-block-cover alignfull"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:cover {"dimRatio":60} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:paragraph {"align":"center"} -->
<p class="wp-block-paragraph has-text-align-center">OPTIONAL EYEBROW</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1} -->
<h1 class="wp-block-heading">Section Landing Page Heading</h1>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->
</div></div>
<!-- /wp:cover -->
</div></div>
<!-- /wp:cover -->
<!-- wp:separator {"className":"stjo-zigzag alignfull"} -->
<hr class="wp-block-separator has-alpha-channel-opacity stjo-zigzag alignfull"/>
<!-- /wp:separator -->

<!-- UNMATCHED SECTION: 'Three Column' (Figma 4948:1631) — generic render; review + consider a registry template -->
<!-- wp:columns {"align":"full"} -->
<div class="wp-block-columns alignfull">
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:columns -->
<div class="wp-block-columns">
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading -->
<h2 class="wp-block-heading">Section Intro Title</h2>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:paragraph -->
<p class="wp-block-paragraph">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->
<!-- UNMATCHED SECTION: 'Three Column' (Figma 4948:1638) — generic render; review + consider a registry template -->
<!-- wp:columns {"align":"full"} -->
<div class="wp-block-columns alignfull">
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:paragraph -->
<p class="wp-block-paragraph">Subsection Link</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:paragraph -->
<p class="wp-block-paragraph">Subsection Link</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:paragraph -->
<p class="wp-block-paragraph">Subsection Link</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:paragraph -->
<p class="wp-block-paragraph">Subsection Link</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->
<!-- wp:separator {"className":"stjo-zigzag alignfull"} -->
<hr class="wp-block-separator has-alpha-channel-opacity stjo-zigzag alignfull"/>
<!-- /wp:separator -->

<!-- UNMATCHED SECTION: 'Three Column' (Figma 4948:1647) — generic render; review + consider a registry template -->
<!-- wp:columns {"align":"full"} -->
<div class="wp-block-columns alignfull">
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Option Video Title</h3>
<!-- /wp:heading -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:image -->
<figure class="wp-block-image"><!-- Image placeholder — Figma node 4948:1650 --></figure>
<!-- /wp:image -->

<!-- wp:group -->
<div class="wp-block-group">

</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->
<!-- wp:group {"className":"stjo-subsection","layout":{"type":"constrained"}} -->
<div class="wp-block-group stjo-subsection"><!-- wp:columns {"verticalAlignment":"center"} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:image {"sizeSlug":"large","className":"is-style-rounded"} -->
<figure class="wp-block-image size-large is-style-rounded"><img src="<?php echo esc_url( $img . '/from-shy-newcomer-to-cultural-leader.png' ); ?>" alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->
<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Subsection Title</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Optional Subhead</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-fill"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link wp-element-button" href="#">Two Button</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:separator {"className":"stjo-zigzag alignfull"} -->
<hr class="wp-block-separator has-alpha-channel-opacity stjo-zigzag alignfull"/>
<!-- /wp:separator -->

<!-- wp:group {"className":"stjo-subsection","layout":{"type":"constrained"}} -->
<div class="wp-block-group stjo-subsection"><!-- wp:columns {"verticalAlignment":"center"} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Subsection Title</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Optional Subhead</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-fill"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link wp-element-button" href="#">Two Button</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons --></div>
<!-- /wp:column -->
<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:image {"sizeSlug":"large","className":"is-style-rounded"} -->
<figure class="wp-block-image size-large is-style-rounded"><img src="<?php echo esc_url( $img . '/from-shy-newcomer-to-cultural-leader.png' ); ?>" alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:separator {"className":"stjo-zigzag alignfull"} -->
<hr class="wp-block-separator has-alpha-channel-opacity stjo-zigzag alignfull"/>
<!-- /wp:separator -->

<!-- wp:group {"className":"stjo-subsection","layout":{"type":"constrained"}} -->
<div class="wp-block-group stjo-subsection"><!-- wp:columns {"verticalAlignment":"center"} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:image {"sizeSlug":"large","className":"is-style-rounded"} -->
<figure class="wp-block-image size-large is-style-rounded"><img src="<?php echo esc_url( $img . '/from-shy-newcomer-to-cultural-leader.png' ); ?>" alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->
<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Subsection Title</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Optional Subhead</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-fill"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link wp-element-button" href="#">Two Button</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:separator {"className":"stjo-zigzag alignfull"} -->
<hr class="wp-block-separator has-alpha-channel-opacity stjo-zigzag alignfull"/>
<!-- /wp:separator -->

<!-- wp:cover {"url":"<?php echo esc_url( $img . '/cover.png' ); ?>","dimRatio":30,"overlayColor":"blue-900","isUserOverlayColor":true,"minHeight":418,"align":"full","className":"stjo-dreammaker"} -->
<div class="wp-block-cover alignfull stjo-dreammaker" style="min-height:418px"><span aria-hidden="true" class="wp-block-cover__background has-blue-900-background-color has-background-dim-30 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( $img . '/cover.png' ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"textAlign":"center","level":2,"textColor":"white","fontSize":"xxl"} -->
<h2 class="wp-block-heading has-text-align-center has-white-color has-text-color has-xxl-font-size">Become a DreamMaker</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"white"} -->
<p class="has-text-align-center has-white-color has-text-color">The DreamMakers are a special group of friends who give automatic monthly gifts to ensure the Lakota (Sioux) children are provided for year-round… <strong>and will help provide dreams for the future.</strong></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button {"className":"btn--light is-style-fill"} -->
<div class="wp-block-button btn--light is-style-fill"><a class="wp-block-button__link wp-element-button" href="#">Give Monthly</a></div>
<!-- /wp:button -->
<!-- wp:button {"className":"btn--light is-style-fill"} -->
<div class="wp-block-button btn--light is-style-fill"><a class="wp-block-button__link wp-element-button" href="#">Learn More</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover -->

<!-- UNMATCHED SECTION: 'Three Column' (Figma 4948:1662) — generic render; review + consider a registry template -->
<!-- wp:columns {"align":"full"} -->
<div class="wp-block-columns alignfull">
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading -->
<h2 class="wp-block-heading">Title</h2>
<!-- /wp:heading -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:paragraph {"align":"center"} -->
<p class="wp-block-paragraph has-text-align-center">Subhead</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:columns -->
<div class="wp-block-columns">
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:cover {"dimRatio":60} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Card / hover</h3>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Explore</a></div>
<!-- /wp:button -->
</div></div>
<!-- /wp:cover -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:cover {"dimRatio":60} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Card / hover</h3>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Explore</a></div>
<!-- /wp:button -->
</div></div>
<!-- /wp:cover -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:cover {"dimRatio":60} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Card / hover</h3>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Explore</a></div>
<!-- /wp:button -->
</div></div>
<!-- /wp:cover -->
</div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:columns -->
<div class="wp-block-columns">
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:cover {"dimRatio":60} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Card / hover</h3>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Explore</a></div>
<!-- /wp:button -->
</div></div>
<!-- /wp:cover -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:cover {"dimRatio":60} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Card / hover</h3>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Explore</a></div>
<!-- /wp:button -->
</div></div>
<!-- /wp:cover -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:cover {"dimRatio":60} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Card / hover</h3>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Explore</a></div>
<!-- /wp:button -->
</div></div>
<!-- /wp:cover -->
</div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->
</div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->
<!-- UNMATCHED SECTION: 'Three Column' (Figma 4948:1675) — generic render; review + consider a registry template -->
<!-- wp:columns {"align":"full"} -->
<div class="wp-block-columns alignfull">
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading -->
<h2 class="wp-block-heading">Cards that open lightboxes</h2>
<!-- /wp:heading -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:paragraph {"align":"center"} -->
<p class="wp-block-paragraph has-text-align-center">Subhead</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:columns -->
<div class="wp-block-columns">
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":4,"textAlign":"center"} -->
<h4 class="wp-block-heading has-text-align-center">Sublink</h4>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:paragraph {"align":"center"} -->
<p class="wp-block-paragraph has-text-align-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Explore</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":4,"textAlign":"center"} -->
<h4 class="wp-block-heading has-text-align-center">Sublink</h4>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:paragraph {"align":"center"} -->
<p class="wp-block-paragraph has-text-align-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Explore</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:columns -->
<div class="wp-block-columns">
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:image -->
<figure class="wp-block-image"><!-- Image placeholder — Figma node I4948:1685;4540:5637 --></figure>
<!-- /wp:image -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":4} -->
<h4 class="wp-block-heading">Lightbox Link</h4>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p class="wp-block-paragraph">Daily language classes ensure the sacred
words of their ancestors live on in the next
generation.</p>
<!-- /wp:paragraph -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Explore</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:image -->
<figure class="wp-block-image"><!-- Image placeholder — Figma node I4948:1686;4540:5637 --></figure>
<!-- /wp:image -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":4} -->
<h4 class="wp-block-heading">Lightbox Link</h4>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p class="wp-block-paragraph">Daily language classes ensure the sacred
words of their ancestors live on in the next
generation.</p>
<!-- /wp:paragraph -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Explore</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:image -->
<figure class="wp-block-image"><!-- Image placeholder — Figma node I4948:1687;4540:5637 --></figure>
<!-- /wp:image -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":4} -->
<h4 class="wp-block-heading">Lightbox Link</h4>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p class="wp-block-paragraph">Daily language classes ensure the sacred
words of their ancestors live on in the next
generation.</p>
<!-- /wp:paragraph -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Explore</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->
</div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->
<!-- wp:separator {"className":"stjo-zigzag alignfull"} -->
<hr class="wp-block-separator has-alpha-channel-opacity stjo-zigzag alignfull"/>
<!-- /wp:separator -->

<!-- UNMATCHED SECTION: 'Four Column' (Figma 4948:1696) — generic render; review + consider a registry template -->
<!-- wp:columns {"align":"full"} -->
<div class="wp-block-columns alignfull">
<!-- wp:column -->
<div class="wp-block-column">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:cover {"dimRatio":60} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Monthly giving</h3>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Give Monthly Now</a></div>
<!-- /wp:button -->
</div></div>
<!-- /wp:cover -->

<!-- wp:cover {"dimRatio":60} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">One-Time Gift</h3>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Give Now</a></div>
<!-- /wp:button -->
</div></div>
<!-- /wp:cover -->

<!-- wp:cover {"dimRatio":60} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Donor  Advised Fund</h3>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Give Now</a></div>
<!-- /wp:button -->
</div></div>
<!-- /wp:cover -->

<!-- wp:cover {"dimRatio":60} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Memorial Gift</h3>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Give Now</a></div>
<!-- /wp:button -->
</div></div>
<!-- /wp:cover -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:image -->
<figure class="wp-block-image"><!-- Image placeholder — Figma node I4948:1704;4226:1674 --></figure>
<!-- /wp:image -->

<!-- wp:image -->
<figure class="wp-block-image"><!-- Image placeholder — Figma node I4948:1704;4226:1675 --></figure>
<!-- /wp:image -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":4,"textAlign":"center"} -->
<h4 class="wp-block-heading has-text-align-center">Planned Giving</h4>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:paragraph {"align":"center"} -->
<p class="wp-block-paragraph has-text-align-center">Leave a lasting legacy</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:image -->
<figure class="wp-block-image"><!-- Image placeholder — Figma node I4948:1705;4226:1724 --></figure>
<!-- /wp:image -->

<!-- wp:image -->
<figure class="wp-block-image"><!-- Image placeholder — Figma node I4948:1705;4226:1725 --></figure>
<!-- /wp:image -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":4,"textAlign":"center"} -->
<h4 class="wp-block-heading has-text-align-center">Donate Your Vehicle</h4>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:paragraph {"align":"center"} -->
<p class="wp-block-paragraph has-text-align-center">Turn your car into hope</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:image -->
<figure class="wp-block-image"><!-- Image placeholder — Figma node I4948:1706;4226:3867 --></figure>
<!-- /wp:image -->

<!-- wp:image -->
<figure class="wp-block-image"><!-- Image placeholder — Figma node I4948:1706;4226:3868 --></figure>
<!-- /wp:image -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":4,"textAlign":"center"} -->
<h4 class="wp-block-heading has-text-align-center">Our Shop</h4>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:paragraph {"align":"center"} -->
<p class="wp-block-paragraph has-text-align-center">Shop handmade Lakota crafts</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:image -->
<figure class="wp-block-image"><!-- Image placeholder — Figma node I4948:1707;4316:2299 --></figure>
<!-- /wp:image -->

<!-- wp:image -->
<figure class="wp-block-image"><!-- Image placeholder — Figma node I4948:1707;4316:2303 --></figure>
<!-- /wp:image -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:heading {"level":4,"textAlign":"center"} -->
<h4 class="wp-block-heading has-text-align-center">Wishlists &amp; Gift Cards</h4>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group">
<!-- wp:paragraph {"align":"center"} -->
<p class="wp-block-paragraph has-text-align-center">Give specific items students need</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:column -->
</div>
<!-- /wp:columns -->