<?php
/**
 * Title: 2-Column: Quote + Donation Widget
 * Categories: ctas
 * Description: Structure: donation-quote. Source: home — Donation Block. Generated by render_patterns.py.
 *
 * @package stjo
 */
?>
<!-- wp:group {"metadata":{"name":"2-Column: Quote + Donation Widget"},"align":"full","backgroundColor":"light","layout":{"type":"constrained"},"className":"stjo-donation-band"} -->
<div class="wp-block-group alignfull stjo-donation-band has-light-background-color has-background"><!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"verticalAlignment":"center"} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">"Because of you, a child woke up today with somewhere safe to call home."</h2>
<!-- /wp:heading --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:stjo/donation-selector /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":"var:preset|spacing|large"} -->
<div style="height:var(--wp--preset--spacing--large)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->
