<?php
/**
 * Title: 2-Column Image and Text
 * Description: Structure: two-column. Source: section-landing — Two Column. Generated by render_patterns.py.
 *
 * @package stjo
 */
?>
<!-- wp:group {"className":"stjo-subsection","layout":{"type":"constrained"}} -->
<div class="wp-block-group stjo-subsection"><!-- wp:columns {"verticalAlignment":"center"} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:image {"sizeSlug":"large","className":"is-style-rounded"} -->
<figure class="wp-block-image size-large is-style-rounded"><img src="<?php echo esc_url( stjo_asset( 'from-shy-newcomer-to-cultural-leader.png' ) ); ?>" alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->
<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Subsection Title</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Optional Subhead</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-fill"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link wp-element-button" href="#">Two Button</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->
